CREATE SEQUENCE  "S33164"."OSOBA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "S33164"."TRANSAKCJA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE OR REPLACE EDITIONABLE TRIGGER "S33164"."OSOBA_TRG" 
BEFORE INSERT ON OSOBA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.S_NUMER IS NULL THEN
      SELECT OSOBA_SEQ.NEXTVAL INTO :NEW.S_NUMER FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "S33164"."OSOBA_TRG" ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "S33164"."TRANSAKCJA_TRG" 
BEFORE INSERT ON TRANSAKCJA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TRANSAKCJA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "S33164"."TRANSAKCJA_TRG" ENABLE;